name: Record animation
on:
  push:
# Uncomment to run every midnight
#  schedule:
#    - cron:  '0 0 * * *'
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Record and deploy the animation
        uses: cyberbotics/webots-animation-action@feature-benchmark
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_PAT_KEY: ${{ secrets.BOT_PAT_KEY }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}